### ISSUE TITLE
version/tag

### ISSUE THREAD

**Issue by ra1nb0w** [SDRplay/RSPTCPServer#1]
Hi,
I am packaging rsp_tcp for MacPorts (package manager for macOS) and could be nice to have a tag (version) which I can refer. In the README I see 0.1.0 but not other reference about that version. What do you think about releasing a version? 1.0.0 as well. You can find more about this topic on [this](https://github.com/SDRplay/RSPTCPServer/releases) page.
Thanks

**Comment by SDRplay** [comment]
Has been done.

**Comment by ra1nb0w** [comment]
thank you!

**Comment by ra1nb0w** [comment]
I see that in the code the version is quite inconsistent. See my PR https://github.com/SDRplay/RSPTCPServer/pull/2 and probably retag the git version with v0.1.0 or change accordingly the code.
