### ISSUE TITLE
shm_open: No such file or directory

### ISSUE THREAD

**Issue by Geremia** [SDRplay/RSPTCPServer#15]
```
$ rsp_tcp 
rsp_tcp version 0.1.0

shm_open: No such file or directory
Cannot connect to API service
```

**Comment by SDRplay** [comment]
Looks like the API isn't running or there's a problem with it. If it's installed, reboot and check that it's running...

ps -edf | grep -i sdrplay

That's not an issue with RSPTCPServer though. The last time this was tested was with API 3.07 so it might also depend on what verison of the API you're using.
