### ISSUE TITLE
Cannot stream to linux

### ISSUE THREAD

**Issue by leftishness** [SDRplay/RSPTCPServer#5]
On the server end, I'm running an RPi 3 with the SDRPlay image running on it, connected to my RSPduo using the Hi-Z antenna. 

On the receiver end, I'm running a fully updated version of Ubuntu Mate 20.04. 

I'm using cubicsdr with soapysdrplay (https://cubicsdr.readthedocs.io/en/stable/building-cubicsdr/linux.html) and attempting to connect to the 'SoapyRemote' option in the EASYplay Menu. Unfortunately, I cannot get anything to come through.

Alternatively, I have been able to see some data come through on gqrx using the 'RSP-TCP server' option but I cannot choose the antenna or tune below 24 MHz.

I'm able to use the RSPduo with the receiver computer just fine if it is plugged in locally via USB. However, getting this to work remotely with the RPi as the server is unsuccessful on my linux machine.

On the other hand, I can connect to and stream just fine from my Windows machine. So, there's something missing on linux frontends that makes accessing the RSPduo remotely not work right. As a linux user, what do I have to do to make this work?

**Comment by SDRplay** [comment]
This TCP server is not compatible with the SoapyRemote client - there is a separate SoapyRemote server application for that.

There is no issue with the TCP server in tuning below 24 MHz, so that's more likely to be an issue at the client end.
